// File auto-generated by stainless.

package opencode

import (
	"github.com/GunsonJack/opencode-sdk-go/internal/apijson"
)

// 1. project.updated — Properties uses existing Project type directly

type EventListResponseEventProjectUpdated struct {
	Properties Project                                    `json:"properties,required"`
	Type       EventListResponseEventProjectUpdatedType   `json:"type,required"`
	JSON       eventListResponseEventProjectUpdatedJSON   `json:"-"`
}

// eventListResponseEventProjectUpdatedJSON contains the JSON metadata for the
// struct [EventListResponseEventProjectUpdated]
type eventListResponseEventProjectUpdatedJSON struct {
	Properties  apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventProjectUpdated) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventProjectUpdatedJSON) RawJSON() string {
	return r.raw
}

func (r EventListResponseEventProjectUpdated) implementsEventListResponse() {}

type EventListResponseEventProjectUpdatedType string

const (
	EventListResponseEventProjectUpdatedTypeProjectUpdated EventListResponseEventProjectUpdatedType = "project.updated"
)

func (r EventListResponseEventProjectUpdatedType) IsKnown() bool {
	switch r {
	case EventListResponseEventProjectUpdatedTypeProjectUpdated:
		return true
	}
	return false
}

// 2. server.instance.disposed — Properties custom struct with Directory

type EventListResponseEventServerInstanceDisposed struct {
	Properties EventListResponseEventServerInstanceDisposedProperties `json:"properties,required"`
	Type       EventListResponseEventServerInstanceDisposedType       `json:"type,required"`
	JSON       eventListResponseEventServerInstanceDisposedJSON       `json:"-"`
}

// eventListResponseEventServerInstanceDisposedJSON contains the JSON metadata for
// the struct [EventListResponseEventServerInstanceDisposed]
type eventListResponseEventServerInstanceDisposedJSON struct {
	Properties  apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventServerInstanceDisposed) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventServerInstanceDisposedJSON) RawJSON() string {
	return r.raw
}

func (r EventListResponseEventServerInstanceDisposed) implementsEventListResponse() {}

type EventListResponseEventServerInstanceDisposedProperties struct {
	Directory string                                                     `json:"directory,required"`
	JSON      eventListResponseEventServerInstanceDisposedPropertiesJSON `json:"-"`
}

// eventListResponseEventServerInstanceDisposedPropertiesJSON contains the JSON
// metadata for the struct [EventListResponseEventServerInstanceDisposedProperties]
type eventListResponseEventServerInstanceDisposedPropertiesJSON struct {
	Directory   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventServerInstanceDisposedProperties) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventServerInstanceDisposedPropertiesJSON) RawJSON() string {
	return r.raw
}

type EventListResponseEventServerInstanceDisposedType string

const (
	EventListResponseEventServerInstanceDisposedTypeServerInstanceDisposed EventListResponseEventServerInstanceDisposedType = "server.instance.disposed"
)

func (r EventListResponseEventServerInstanceDisposedType) IsKnown() bool {
	switch r {
	case EventListResponseEventServerInstanceDisposedTypeServerInstanceDisposed:
		return true
	}
	return false
}

// 3. global.disposed — Properties is interface{} (empty)

type EventListResponseEventGlobalDisposed struct {
	Properties interface{}                                `json:"properties,required"`
	Type       EventListResponseEventGlobalDisposedType   `json:"type,required"`
	JSON       eventListResponseEventGlobalDisposedJSON   `json:"-"`
}

// eventListResponseEventGlobalDisposedJSON contains the JSON metadata for the
// struct [EventListResponseEventGlobalDisposed]
type eventListResponseEventGlobalDisposedJSON struct {
	Properties  apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventGlobalDisposed) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventGlobalDisposedJSON) RawJSON() string {
	return r.raw
}

func (r EventListResponseEventGlobalDisposed) implementsEventListResponse() {}

type EventListResponseEventGlobalDisposedType string

const (
	EventListResponseEventGlobalDisposedTypeGlobalDisposed EventListResponseEventGlobalDisposedType = "global.disposed"
)

func (r EventListResponseEventGlobalDisposedType) IsKnown() bool {
	switch r {
	case EventListResponseEventGlobalDisposedTypeGlobalDisposed:
		return true
	}
	return false
}

// 4. lsp.updated — Properties is interface{} (empty)

type EventListResponseEventLspUpdated struct {
	Properties interface{}                            `json:"properties,required"`
	Type       EventListResponseEventLspUpdatedType   `json:"type,required"`
	JSON       eventListResponseEventLspUpdatedJSON   `json:"-"`
}

// eventListResponseEventLspUpdatedJSON contains the JSON metadata for the struct
// [EventListResponseEventLspUpdated]
type eventListResponseEventLspUpdatedJSON struct {
	Properties  apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventLspUpdated) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventLspUpdatedJSON) RawJSON() string {
	return r.raw
}

func (r EventListResponseEventLspUpdated) implementsEventListResponse() {}

type EventListResponseEventLspUpdatedType string

const (
	EventListResponseEventLspUpdatedTypeLspUpdated EventListResponseEventLspUpdatedType = "lsp.updated"
)

func (r EventListResponseEventLspUpdatedType) IsKnown() bool {
	switch r {
	case EventListResponseEventLspUpdatedTypeLspUpdated:
		return true
	}
	return false
}

// 5. installation.update-available — custom Properties with Version

type EventListResponseEventInstallationUpdateAvailable struct {
	Properties EventListResponseEventInstallationUpdateAvailableProperties `json:"properties,required"`
	Type       EventListResponseEventInstallationUpdateAvailableType       `json:"type,required"`
	JSON       eventListResponseEventInstallationUpdateAvailableJSON       `json:"-"`
}

// eventListResponseEventInstallationUpdateAvailableJSON contains the JSON metadata
// for the struct [EventListResponseEventInstallationUpdateAvailable]
type eventListResponseEventInstallationUpdateAvailableJSON struct {
	Properties  apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventInstallationUpdateAvailable) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventInstallationUpdateAvailableJSON) RawJSON() string {
	return r.raw
}

func (r EventListResponseEventInstallationUpdateAvailable) implementsEventListResponse() {}

type EventListResponseEventInstallationUpdateAvailableProperties struct {
	Version string                                                          `json:"version,required"`
	JSON    eventListResponseEventInstallationUpdateAvailablePropertiesJSON `json:"-"`
}

// eventListResponseEventInstallationUpdateAvailablePropertiesJSON contains the
// JSON metadata for the struct
// [EventListResponseEventInstallationUpdateAvailableProperties]
type eventListResponseEventInstallationUpdateAvailablePropertiesJSON struct {
	Version     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventInstallationUpdateAvailableProperties) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventInstallationUpdateAvailablePropertiesJSON) RawJSON() string {
	return r.raw
}

type EventListResponseEventInstallationUpdateAvailableType string

const (
	EventListResponseEventInstallationUpdateAvailableTypeInstallationUpdateAvailable EventListResponseEventInstallationUpdateAvailableType = "installation.update-available"
)

func (r EventListResponseEventInstallationUpdateAvailableType) IsKnown() bool {
	switch r {
	case EventListResponseEventInstallationUpdateAvailableTypeInstallationUpdateAvailable:
		return true
	}
	return false
}

// 6. message.part.delta — custom Properties with multiple fields

type EventListResponseEventMessagePartDelta struct {
	Properties EventListResponseEventMessagePartDeltaProperties `json:"properties,required"`
	Type       EventListResponseEventMessagePartDeltaType       `json:"type,required"`
	JSON       eventListResponseEventMessagePartDeltaJSON       `json:"-"`
}

// eventListResponseEventMessagePartDeltaJSON contains the JSON metadata for the
// struct [EventListResponseEventMessagePartDelta]
type eventListResponseEventMessagePartDeltaJSON struct {
	Properties  apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventMessagePartDelta) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventMessagePartDeltaJSON) RawJSON() string {
	return r.raw
}

func (r EventListResponseEventMessagePartDelta) implementsEventListResponse() {}

type EventListResponseEventMessagePartDeltaProperties struct {
	SessionID string                                               `json:"sessionID,required"`
	MessageID string                                               `json:"messageID,required"`
	PartID    string                                               `json:"partID,required"`
	Field     string                                               `json:"field,required"`
	Delta     string                                               `json:"delta,required"`
	JSON      eventListResponseEventMessagePartDeltaPropertiesJSON `json:"-"`
}

// eventListResponseEventMessagePartDeltaPropertiesJSON contains the JSON metadata
// for the struct [EventListResponseEventMessagePartDeltaProperties]
type eventListResponseEventMessagePartDeltaPropertiesJSON struct {
	SessionID   apijson.Field
	MessageID   apijson.Field
	PartID      apijson.Field
	Field       apijson.Field
	Delta       apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventMessagePartDeltaProperties) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventMessagePartDeltaPropertiesJSON) RawJSON() string {
	return r.raw
}

type EventListResponseEventMessagePartDeltaType string

const (
	EventListResponseEventMessagePartDeltaTypeMessagePartDelta EventListResponseEventMessagePartDeltaType = "message.part.delta"
)

func (r EventListResponseEventMessagePartDeltaType) IsKnown() bool {
	switch r {
	case EventListResponseEventMessagePartDeltaTypeMessagePartDelta:
		return true
	}
	return false
}

// 7. permission.asked — Properties uses existing PermissionRequest type directly

type EventListResponseEventPermissionAsked struct {
	Properties PermissionRequest                              `json:"properties,required"`
	Type       EventListResponseEventPermissionAskedType      `json:"type,required"`
	JSON       eventListResponseEventPermissionAskedJSON      `json:"-"`
}

// eventListResponseEventPermissionAskedJSON contains the JSON metadata for the
// struct [EventListResponseEventPermissionAsked]
type eventListResponseEventPermissionAskedJSON struct {
	Properties  apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventPermissionAsked) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventPermissionAskedJSON) RawJSON() string {
	return r.raw
}

func (r EventListResponseEventPermissionAsked) implementsEventListResponse() {}

type EventListResponseEventPermissionAskedType string

const (
	EventListResponseEventPermissionAskedTypePermissionAsked EventListResponseEventPermissionAskedType = "permission.asked"
)

func (r EventListResponseEventPermissionAskedType) IsKnown() bool {
	switch r {
	case EventListResponseEventPermissionAskedTypePermissionAsked:
		return true
	}
	return false
}

// 8. session.diff — custom Properties with SessionID and Diff

type EventListResponseEventSessionDiff struct {
	Properties EventListResponseEventSessionDiffProperties `json:"properties,required"`
	Type       EventListResponseEventSessionDiffType       `json:"type,required"`
	JSON       eventListResponseEventSessionDiffJSON       `json:"-"`
}

// eventListResponseEventSessionDiffJSON contains the JSON metadata for the struct
// [EventListResponseEventSessionDiff]
type eventListResponseEventSessionDiffJSON struct {
	Properties  apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventSessionDiff) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventSessionDiffJSON) RawJSON() string {
	return r.raw
}

func (r EventListResponseEventSessionDiff) implementsEventListResponse() {}

type EventListResponseEventSessionDiffProperties struct {
	SessionID string                                          `json:"sessionID,required"`
	Diff      []SnapshotFileDiff                              `json:"diff,required"`
	JSON      eventListResponseEventSessionDiffPropertiesJSON `json:"-"`
}

// eventListResponseEventSessionDiffPropertiesJSON contains the JSON metadata for
// the struct [EventListResponseEventSessionDiffProperties]
type eventListResponseEventSessionDiffPropertiesJSON struct {
	SessionID   apijson.Field
	Diff        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventSessionDiffProperties) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventSessionDiffPropertiesJSON) RawJSON() string {
	return r.raw
}

type EventListResponseEventSessionDiffType string

const (
	EventListResponseEventSessionDiffTypeSessionDiff EventListResponseEventSessionDiffType = "session.diff"
)

func (r EventListResponseEventSessionDiffType) IsKnown() bool {
	switch r {
	case EventListResponseEventSessionDiffTypeSessionDiff:
		return true
	}
	return false
}

// 9. session.status — custom Properties with SessionID and Status

type EventListResponseEventSessionStatus struct {
	Properties EventListResponseEventSessionStatusProperties `json:"properties,required"`
	Type       EventListResponseEventSessionStatusType       `json:"type,required"`
	JSON       eventListResponseEventSessionStatusJSON       `json:"-"`
}

// eventListResponseEventSessionStatusJSON contains the JSON metadata for the
// struct [EventListResponseEventSessionStatus]
type eventListResponseEventSessionStatusJSON struct {
	Properties  apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventSessionStatus) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventSessionStatusJSON) RawJSON() string {
	return r.raw
}

func (r EventListResponseEventSessionStatus) implementsEventListResponse() {}

type EventListResponseEventSessionStatusProperties struct {
	SessionID string                                            `json:"sessionID,required"`
	Status    SessionStatus                                     `json:"status,required"`
	JSON      eventListResponseEventSessionStatusPropertiesJSON `json:"-"`
}

// eventListResponseEventSessionStatusPropertiesJSON contains the JSON metadata for
// the struct [EventListResponseEventSessionStatusProperties]
type eventListResponseEventSessionStatusPropertiesJSON struct {
	SessionID   apijson.Field
	Status      apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventSessionStatusProperties) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventSessionStatusPropertiesJSON) RawJSON() string {
	return r.raw
}

type EventListResponseEventSessionStatusType string

const (
	EventListResponseEventSessionStatusTypeSessionStatus EventListResponseEventSessionStatusType = "session.status"
)

func (r EventListResponseEventSessionStatusType) IsKnown() bool {
	switch r {
	case EventListResponseEventSessionStatusTypeSessionStatus:
		return true
	}
	return false
}

// 10. question.asked — Properties uses existing QuestionRequest type directly

type EventListResponseEventQuestionAsked struct {
	Properties QuestionRequest                              `json:"properties,required"`
	Type       EventListResponseEventQuestionAskedType      `json:"type,required"`
	JSON       eventListResponseEventQuestionAskedJSON      `json:"-"`
}

// eventListResponseEventQuestionAskedJSON contains the JSON metadata for the
// struct [EventListResponseEventQuestionAsked]
type eventListResponseEventQuestionAskedJSON struct {
	Properties  apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *EventListResponseEventQuestionAsked) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r eventListResponseEventQuestionAskedJSON) RawJSON() string {
	return r.raw
}

func (r EventListResponseEventQuestionAsked) implementsEventListResponse() {}

type EventListResponseEventQuestionAskedType string

const (
	EventListResponseEventQuestionAskedTypeQuestionAsked EventListResponseEventQuestionAskedType = "question.asked"
)

func (r EventListResponseEventQuestionAskedType) IsKnown() bool {
	switch r {
	case EventListResponseEventQuestionAskedTypeQuestionAsked:
		return true
	}
	return false
}
